# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Serially compute square root of matrix elements
#'
#' @param orig A matrix
#'
#' @returns A matrix in which each element is the square root of the corresponding element in the original matrix
#'
#' @examples
#' m <- matrix(as.numeric(c(1:1000000)), nrow = 1000, ncol = 1000)
#' matrixSqrt(m)
#' @export
matrixSqrt <- function(orig) {
    .Call('_testRcppParallel_matrixSqrt', PACKAGE = 'testRcppParallel', orig)
}

